name = "f1-fandom"
main = "src/index.ts"
compatibility_date = "2024-03-20"
workers_dev = false
preview_urls = false

# Environment variables that can be overridden
[vars]
DEFAULT_WIKI_DOMAIN = "f1.fandom.com"
TURNSTILE_SITE_KEY = "0x4AAAAAABoDGtBnq2BXlSqW"

# Bindings (e.g. Secrets, KV) would go here if needed.
# WIKI_BOT_USERNAME and WIKI_BOT_PASSWORD can be added via Cloudflare dashboard or `wrangler secret put`

[triggers]
crons = ["*/10 * * * *", "0 * * * *"]

[[kv_namespaces]]
binding = "F1_WIKI_STATE"
id = "65451fd50ac0476e85b50e3118b1e5ea"

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1
